### ISSUE TITLE
[Login / Signup] Add error handling and form validations 

### ISSUE THREAD

**Issue by Pooja-Lohar25** [ojasaklechayt/Oju-s-Blogs#13]
1. Login and signup forms are irresponsive in case of errors and wrong inputs
2. The forms accept invalid data as well like name = 123

I would like to work on it.
@ojasaklechayt Kindly assign me this issue under hacktoberfest .

**Comment by ojasaklechayt** [comment]
@Pooja-Lohar25 Go for it

**Comment by ojasaklechayt** [comment]
@Pooja-Lohar25 I feel this issue is already been handled by somebody else. May be you can try testing that out and further enhancing that out.

**Comment by Pooja-Lohar25** [comment]
I see it only displays the messages for blank inputs so I will add error-handling and form validations code with that to enhance.
