### ISSUE TITLE
[Add Blog feature] Adding Validation to Image field while posting a blog

### ISSUE THREAD

**Issue by MukulVashishth** [ojasaklechayt/Oju-s-Blogs#17]
Observed an issue while creating a new blog that we can populate any invalid data in the image field. 

As a result the image is not rendered.

![image](https://github.com/ojasaklechayt/Oju-s-Blogs/assets/67701494/c9a55c22-247f-47a4-bcd8-2ec8d34b76e4)

![image](https://github.com/ojasaklechayt/Oju-s-Blogs/assets/67701494/0bd48312-9de3-4a3e-935d-2ae2e1499d1f)

I can work on this.
@ojasaklechayt Can you please assign this issue to me under hacktoberfest .

**Comment by ojasaklechayt** [comment]
How do you plan to fix it ?

**Comment by MukulVashishth** [comment]
We have 2 options for this :

i) We can make the user to upload an image by providing that option instead of pasting the link.

ii) If we need to keep the 'ImageURL' field then we need to keep a regex validation for URL validation.

**Comment by ojasaklechayt** [comment]
> We have 2 options for this :
> 
> i) We can make the user to upload an image by providing that option instead of pasting the link.
> 
> ii) If we need to keep the 'ImageURL' field then we need to keep a regex validation for URL validation.

I would recommend to go for user to upload the photo instead of pasting the link

**Comment by ojasaklechayt** [comment]
@MukulVashishth I feel we need to update backend also for this. Please do have look if soo.

**Comment by aasimtaif** [comment]
> @MukulVashishth I feel we need to update backend also for this. Please do have look if soo.

you do not need to update the backend for this you just have to convert image to base64 and pass it as a string to backend
