### ISSUE TITLE
Back to top button!

### ISSUE THREAD

**Issue by Nupur19nj** [ojasaklechayt/Oju-s-Blogs#26]
There is not back to top button in blogs page and so user needs to scroll all the way to top again !
I want to add a button on clicking which user can go to top again
![image](https://github.com/ojasaklechayt/Oju-s-Blogs/assets/114866308/e83bdc45-d399-4b6e-a9f2-17ee2682f7c6)
please assign me this under hacktober-accepted!

**Comment by ojasaklechayt** [comment]
Please try to keep it minimalistic

**Comment by Nupur19nj** [comment]
Ya sure! Thanks
