### ISSUE TITLE
Update the CONTRIBUTING.md file and write basic contribution instructions

### ISSUE THREAD

**Issue by ojasaklechayt** [ojasaklechayt/Oju-s-Blogs#3]
I have created a CONTRIBUTING.md file kindly write the basic instructions for the contributions

**Comment by adarsht0001** [comment]
can u  assign me this issue

**Comment by ojasaklechayt** [comment]
@adarsht0001 Assigned

**Comment by adarsht0001** [comment]
i have created a pr for the issue. please let me know if any edits is needed
