### ISSUE TITLE
React Toastify to Display messages

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [ojasaklechayt/Oju-s-Blogs#9]
In the login , sign up page if while user is filling his fields and if he left any one filed and then if he clicked on the sign up or Login it is not showing any message ;

I want to add a message that user can understand that he has to fill specific fields as well ;

I will do this by using React Toastify Library : )

for example --------------------------------->

https://github.com/ojasaklechayt/Oju-s-Blogs/assets/127650446/4b8867ce-37df-40d5-9cf6-e149b2fbd4b3

can you assign this to me , _Hacktoberfest_2023 : )

**Comment by ojasaklechayt** [comment]
@Bharath-KumarReddy I will assign you this. Please also add the toast when user gives wrong credentials. Also before making PR please follow the general PR rules like titling the pr with correct name, mentioning the issue number using # issue number format. Also add a little description about your changes there in the PR.

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I resolved this issue and I made a PR #21  once check : )
